export const countryCodes = [
  {
    name: "افغانستان",
    code: "AF",
    dial_code: "+93",
    phone_digits_count: "9~9",
  },
  { name: "Åland", code: "AX", dial_code: "+358", phone_digits_count: "15~15" },
  {
    name: "Shqipëria",
    code: "AL",
    dial_code: "+355",
    phone_digits_count: "9~9",
  },
  { name: "الجزائر", code: "DZ", dial_code: "+213", phone_digits_count: "9~9" },
  {
    name: "American Samoa",
    code: "AS",
    dial_code: "+1684",
    phone_digits_count: "7~7",
  },
  { name: "Andorra", code: "AD", dial_code: "+376", phone_digits_count: "9~9" },
  { name: "Angola", code: "AO", dial_code: "+244", phone_digits_count: "9~9" },
  {
    name: "Anguilla",
    code: "AI",
    dial_code: "+1264",
    phone_digits_count: "7~7",
  },

  {
    name: "Antarctica",
    code: "AQ",
    dial_code: "+672",
    phone_digits_count: "6~6",
  },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    dial_code: "+1268",
    phone_digits_count: "7~7",
  },
  {
    name: "Argentina",
    code: "AR",
    dial_code: "+54",
    phone_digits_count: "12~12",
  },
  {
    name: "Հայաստան",
    code: "AM",
    dial_code: "+374",
    phone_digits_count: "8~8",
  },
  { name: "Aruba", code: "AW", dial_code: "+297", phone_digits_count: "7~7" },
  {
    name: "Australia",
    code: "AU",
    dial_code: "+61",
    phone_digits_count: "9~9",
  },
  {
    name: "Österreich",
    code: "AT",
    dial_code: "+43",
    phone_digits_count: "13~13",
  },
  {
    name: "Azərbaycan",
    code: "AZ",
    dial_code: "+994",
    phone_digits_count: "9~9",
  },
  {
    name: "Bahamas",
    code: "BS",
    dial_code: "+1242",
    phone_digits_count: "7~7",
  },
  {
    name: "‏البحرين",
    code: "BH",
    dial_code: "+973",
    phone_digits_count: "8~8",
  },
  {
    name: "Bangladesh",
    code: "BD",
    dial_code: "+880",
    phone_digits_count: "10~10",
  },
  {
    name: "Barbados",
    code: "BB",
    dial_code: "+1246",
    phone_digits_count: "7~7",
  },
  {
    name: "Белару́сь",
    code: "BY",
    dial_code: "+375",
    phone_digits_count: "10~10",
  },
  { name: "België", code: "BE", dial_code: "+32", phone_digits_count: "9~9" },
  { name: "Belize", code: "BZ", dial_code: "+501", phone_digits_count: "7~7" },
  { name: "Bénin", code: "BJ", dial_code: "+229", phone_digits_count: "8~8" },
  {
    name: "Bermuda",
    code: "BM",
    dial_code: "+1441",
    phone_digits_count: "7~7",
  },
  {
    name: "ʼbrug-yul",
    code: "BT",
    dial_code: "+975",
    phone_digits_count: "8~8",
  },
  { name: "Bolivia", code: "BO", dial_code: "+591", phone_digits_count: "8~8" },
  {
    name: "Bosna i Hercegovina",
    code: "BA",
    dial_code: "+387",
    phone_digits_count: "9~9",
  },
  {
    name: "Botswana",
    code: "BW",
    dial_code: "+267",
    phone_digits_count: "8~8",
  },
  {
    name: "Bouvetøya",
    code: "BV",
    dial_code: "+47",
    phone_digits_count: "15~15",
  },
  { name: "Brasil", code: "BR", dial_code: "+55", phone_digits_count: "11~11" },
  {
    name: "British Indian Ocean Territory",
    code: "IO",
    dial_code: "+246",
    phone_digits_count: "7~7",
  },
  {
    name: "Negara Brunei Darussalam",
    code: "BN",
    dial_code: "+673",
    phone_digits_count: "7~7",
  },
  {
    name: "България",
    code: "BG",
    dial_code: "+359",
    phone_digits_count: "9~9",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    dial_code: "+226",
    phone_digits_count: "8~8",
  },
  { name: "Burundi", code: "BI", dial_code: "+257", phone_digits_count: "8~8" },
  {
    name: "Cambodia",
    code: "KH",
    dial_code: "+855",
    phone_digits_count: "9~9",
  },
  {
    name: "Cameroon",
    code: "CM",
    dial_code: "+237",
    phone_digits_count: "9~9",
  },
  { name: "Canada", code: "CA", dial_code: "+1", phone_digits_count: "10~10" },
  {
    name: "Cabo Verde",
    code: "CV",
    dial_code: "+238",
    phone_digits_count: "7~7",
  },
  {
    name: "Cayman Islands",
    code: "KY",
    dial_code: "+1345",
    phone_digits_count: "7~7",
  },
  {
    name: "Ködörösêse tî Bêafrîka",
    code: "CF",
    dial_code: "+236",
    phone_digits_count: "8~8",
  },
  { name: "Tchad", code: "TD", dial_code: "+235", phone_digits_count: "7~7" },
  { name: "Chile", code: "CL", dial_code: "+56", phone_digits_count: "9~9" },
  { name: "中国", code: "CN", dial_code: "+86", phone_digits_count: "12~12" },
  {
    name: "Christmas Island",
    code: "CX",
    dial_code: "+61",
    phone_digits_count: "15~15",
  },
  {
    name: "Cocos (Keeling) Islands",
    code: "CC",
    dial_code: "+61",
    phone_digits_count: "15~15",
  },
  {
    name: "Colombia",
    code: "CO",
    dial_code: "+57",
    phone_digits_count: "10~10",
  },
  { name: "Komori", code: "KM", dial_code: "+269", phone_digits_count: "7~7" },
  {
    name: "République du Congo",
    code: "CG",
    dial_code: "+242",
    phone_digits_count: "7~7",
  },
  {
    name: "République démocratique du Congo",
    code: "CD",
    dial_code: "+243",
    phone_digits_count: "9~9",
  },
  {
    name: "Cook Islands",
    code: "CK",
    dial_code: "+682",
    phone_digits_count: "5~5",
  },
  {
    name: "Costa Rica",
    code: "CR",
    dial_code: "+506",
    phone_digits_count: "8~8",
  },
  {
    name: "Côte d'Ivoire",
    code: "CI",
    dial_code: "+225",
    phone_digits_count: "10~10",
  },
  {
    name: "Hrvatska",
    code: "HR",
    dial_code: "+385",
    phone_digits_count: "12~12",
  },
  { name: "Cuba", code: "CU", dial_code: "+53", phone_digits_count: "8~8" },
  { name: "Κύπρος", code: "CY", dial_code: "+357", phone_digits_count: "8~8" },
  {
    name: "Česká republika",
    code: "CZ",
    dial_code: "+420",
    phone_digits_count: "9~9",
  },
  { name: "Danmark", code: "DK", dial_code: "+45", phone_digits_count: "8~8" },
  {
    name: "Djibouti",
    code: "DJ",
    dial_code: "+253",
    phone_digits_count: "6~6",
  },
  {
    name: "Dominica",
    code: "DM",
    dial_code: "+1767",
    phone_digits_count: "7~7",
  },
  {
    name: "República Dominicana",
    code: "DO",
    dial_code: "+1",
    phone_digits_count: "12~12",
  },
  { name: "Ecuador", code: "EC", dial_code: "+593", phone_digits_count: "8~8" },
  { name: "مصر‎", code: "EG", dial_code: "+20", phone_digits_count: "10~10" },
  {
    name: "El Salvador",
    code: "SV",
    dial_code: "+503",
    phone_digits_count: "11~11",
  },
  {
    name: "Guinea Ecuatorial",
    code: "GQ",
    dial_code: "+240",
    phone_digits_count: "6~6",
  },
  { name: "ኤርትራ", code: "ER", dial_code: "+291", phone_digits_count: "7~7" },
  { name: "Eesti", code: "EE", dial_code: "+372", phone_digits_count: "10~10" },
  { name: "ኢትዮጵያ", code: "ET", dial_code: "+251", phone_digits_count: "9~9" },
  {
    name: "Falkland Islands",
    code: "FK",
    dial_code: "+500",
    phone_digits_count: "5~5",
  },
  { name: "Føroyar", code: "FO", dial_code: "+298", phone_digits_count: "6~6" },
  { name: "Fiji", code: "FJ", dial_code: "+679", phone_digits_count: "7~7" },
  { name: "Suomi", code: "FI", dial_code: "+358", phone_digits_count: "12~12" },
  { name: "France", code: "FR", dial_code: "+33", phone_digits_count: "9~9" },
  {
    name: "Guyane française",
    code: "GF",
    dial_code: "+594",
    phone_digits_count: "15~15",
  },
  {
    name: "Polynésie française",
    code: "PF",
    dial_code: "+689",
    phone_digits_count: "6~6",
  },
  {
    name: "Territoire des Terres australes et antarctiques fr",
    code: "TF",
    dial_code: "+262",
    phone_digits_count: "15~15",
  },
  { name: "Gabon", code: "GA", dial_code: "+241", phone_digits_count: "9~9" },
  { name: "Gambia", code: "GM", dial_code: "+220", phone_digits_count: "7~7" },
  {
    name: "საქართველო",
    code: "GE",
    dial_code: "+995",
    phone_digits_count: "8~8",
  },
  {
    name: "Deutschland",
    code: "DE",
    dial_code: "+49",
    phone_digits_count: "9~13",
  },
  { name: "Ghana", code: "GH", dial_code: "+233", phone_digits_count: "10~10" },
  {
    name: "Gibraltar",
    code: "GI",
    dial_code: "+350",
    phone_digits_count: "8~8",
  },
  { name: "Ελλάδα", code: "GR", dial_code: "+30", phone_digits_count: "10~10" },
  {
    name: "Kalaallit Nunaat",
    code: "GL",
    dial_code: "+299",
    phone_digits_count: "6~6",
  },
  {
    name: "Grenada",
    code: "GD",
    dial_code: "+1473",
    phone_digits_count: "7~7",
  },
  {
    name: "Guadeloupe",
    code: "GP",
    dial_code: "+590",
    phone_digits_count: "15~15",
  },
  { name: "Guam", code: "GU", dial_code: "+1671", phone_digits_count: "7~7" },
  {
    name: "Guatemala",
    code: "GT",
    dial_code: "+502",
    phone_digits_count: "8~8",
  },
  { name: "Guernsey", code: "GG", dial_code: "+44", phone_digits_count: "6~6" },
  { name: "Guinée", code: "GN", dial_code: "+224", phone_digits_count: "8~9" },
  {
    name: "Guiné-Bissau",
    code: "GW",
    dial_code: "+245",
    phone_digits_count: "7~7",
  },
  { name: "Guyana", code: "GY", dial_code: "+592", phone_digits_count: "7~7" },
  { name: "Haïti", code: "HT", dial_code: "+509", phone_digits_count: "8~8" },
  {
    name: "Heard Island and McDonald Islands",
    code: "HM",
    dial_code: "+0",
    phone_digits_count: "15~15",
  },
  {
    name: "Vaticano",
    code: "VA",
    dial_code: "+379",
    phone_digits_count: "10~10",
  },
  {
    name: "Honduras",
    code: "HN",
    dial_code: "+504",
    phone_digits_count: "8~8",
  },
  { name: "香港", code: "HK", dial_code: "+852", phone_digits_count: "8~8" },
  {
    name: "Magyarország",
    code: "HU",
    dial_code: "+36",
    phone_digits_count: "9~9",
  },
  { name: "Ísland", code: "IS", dial_code: "+354", phone_digits_count: "7~9" },
  { name: "भारत", code: "IN", dial_code: "+91", phone_digits_count: "10~10" },
  {
    name: "Indonesia",
    code: "ID",
    dial_code: "+62",
    phone_digits_count: "13~13",
  },
  { name: "ایران", code: "IR", dial_code: "+98", phone_digits_count: "10~10" },
  {
    name: "العراق",
    code: "IQ",
    dial_code: "+964",
    phone_digits_count: "10~10",
  },
  { name: "Éire", code: "IE", dial_code: "+353", phone_digits_count: "7~9" },
  {
    name: "Isle of Man",
    code: "IM",
    dial_code: "+44",
    phone_digits_count: "6~6",
  },
  { name: "ישראל", code: "IL", dial_code: "+972", phone_digits_count: "9~9" },
  { name: "Italia", code: "IT", dial_code: "+39", phone_digits_count: "13~13" },
  {
    name: "Jamaica",
    code: "JM",
    dial_code: "+1876",
    phone_digits_count: "7~7",
  },
  { name: "日本", code: "JP", dial_code: "+81", phone_digits_count: "10~10" },
  { name: "Jersey", code: "JE", dial_code: "+44", phone_digits_count: "6~6" },
  { name: "الأردن", code: "JO", dial_code: "+962", phone_digits_count: "9~9" },
  {
    name: "Қазақстан",
    code: "KZ",
    dial_code: "+7",
    phone_digits_count: "10~10",
  },
  { name: "Kenya", code: "KE", dial_code: "+254", phone_digits_count: "10~10" },
  {
    name: "Kiribati",
    code: "KI",
    dial_code: "+686",
    phone_digits_count: "5~5",
  },
  { name: "북한", code: "KP", dial_code: "+850", phone_digits_count: "10~10" },
  {
    name: "대한민국",
    code: "KR",
    dial_code: "+82",
    phone_digits_count: "11~11",
  },
  {
    name: "Republika e Kosovës",
    code: "XK",
    dial_code: "+383",
    phone_digits_count: "8~8",
  },
  { name: "الكويت", code: "KW", dial_code: "+965", phone_digits_count: "8~8" },
  {
    name: "Кыргызстан",
    code: "KG",
    dial_code: "+996",
    phone_digits_count: "9~9",
  },
  { name: "ສປປລາວ", code: "LA", dial_code: "+856", phone_digits_count: "9~9" },
  { name: "Latvija", code: "LV", dial_code: "+371", phone_digits_count: "8~8" },
  { name: "لبنان", code: "LB", dial_code: "+961", phone_digits_count: "8~8" },
  { name: "Lesotho", code: "LS", dial_code: "+266", phone_digits_count: "8~8" },
  { name: "Liberia", code: "LR", dial_code: "+231", phone_digits_count: "8~8" },
  { name: "‏ليبيا", code: "LY", dial_code: "+218", phone_digits_count: "9~9" },
  {
    name: "Liechtenstein",
    code: "LI",
    dial_code: "+423",
    phone_digits_count: "9~9",
  },
  { name: "Lietuva", code: "LT", dial_code: "+370", phone_digits_count: "8~8" },
  {
    name: "Luxembourg",
    code: "LU",
    dial_code: "+352",
    phone_digits_count: "11~11",
  },
  { name: "澳門", code: "MO", dial_code: "+853", phone_digits_count: "8~8" },
  {
    name: "Македонија",
    code: "MK",
    dial_code: "+389",
    phone_digits_count: "8~8",
  },
  {
    name: "Madagasikara",
    code: "MG",
    dial_code: "+261",
    phone_digits_count: "10~10",
  },
  { name: "Malawi", code: "MW", dial_code: "+265", phone_digits_count: "7~9" },
  {
    name: "Malaysia",
    code: "MY",
    dial_code: "+60",
    phone_digits_count: "11~11",
  },
  {
    name: "Maldives",
    code: "MV",
    dial_code: "+960",
    phone_digits_count: "7~7",
  },
  { name: "Mali", code: "ML", dial_code: "+223", phone_digits_count: "8~8" },
  { name: "Malta", code: "MT", dial_code: "+356", phone_digits_count: "8~8" },
  { name: "M̧ajeļ", code: "MH", dial_code: "+692", phone_digits_count: "7~7" },
  {
    name: "Martinique",
    code: "MQ",
    dial_code: "+596",
    phone_digits_count: "15~15",
  },
  {
    name: "موريتانيا",
    code: "MR",
    dial_code: "+222",
    phone_digits_count: "8~8",
  },
  { name: "Maurice", code: "MU", dial_code: "+230", phone_digits_count: "7~8" },
  { name: "Mayotte", code: "YT", dial_code: "+262", phone_digits_count: "9~9" },
  { name: "México", code: "MX", dial_code: "+52", phone_digits_count: "10~10" },
  {
    name: "Micronesia",
    code: "FM",
    dial_code: "+691",
    phone_digits_count: "7~7",
  },
  { name: "Moldova", code: "MD", dial_code: "+373", phone_digits_count: "8~8" },
  { name: "Monaco", code: "MC", dial_code: "+377", phone_digits_count: "9~9" },
  {
    name: "Монгол улс",
    code: "MN",
    dial_code: "+976",
    phone_digits_count: "8~8",
  },
  {
    name: "Црна Гора",
    code: "ME",
    dial_code: "+382",
    phone_digits_count: "12~12",
  },
  {
    name: "Montserrat",
    code: "MS",
    dial_code: "+1664",
    phone_digits_count: "7~7",
  },
  { name: "المغرب", code: "MA", dial_code: "+212", phone_digits_count: "9~9" },
  {
    name: "Moçambique",
    code: "MZ",
    dial_code: "+258",
    phone_digits_count: "9~9",
  },
  { name: "Myanmar", code: "MM", dial_code: "+95", phone_digits_count: "9~9" },
  {
    name: "Namibia",
    code: "NA",
    dial_code: "+264",
    phone_digits_count: "10~10",
  },
  { name: "Nauru", code: "NR", dial_code: "+674", phone_digits_count: "7~7" },
  { name: "नेपाल", code: "NP", dial_code: "+977", phone_digits_count: "10~10" },
  {
    name: "Nederland",
    code: "NL",
    dial_code: "+31",
    phone_digits_count: "9~9",
  },
  {
    name: "Netherlands Antilles",
    code: "AN",
    dial_code: "+599",
    phone_digits_count: "8~8",
  },
  {
    name: "Nouvelle-Calédonie",
    code: "NC",
    dial_code: "+687",
    phone_digits_count: "6~6",
  },
  {
    name: "New Zealand",
    code: "NZ",
    dial_code: "+64",
    phone_digits_count: "10~10",
  },
  {
    name: "Nicaragua",
    code: "NI",
    dial_code: "+505",
    phone_digits_count: "8~8",
  },
  { name: "Niger", code: "NE", dial_code: "+227", phone_digits_count: "8~8" },
  {
    name: "Nigeria",
    code: "NG",
    dial_code: "+234",
    phone_digits_count: "10~11",
  },
  { name: "Niuē", code: "NU", dial_code: "+683", phone_digits_count: "4~4" },
  {
    name: "Norfolk Island",
    code: "NF",
    dial_code: "+672",
    phone_digits_count: "15~15",
  },
  {
    name: "Northern Mariana Islands",
    code: "MP",
    dial_code: "+1670",
    phone_digits_count: "7~7",
  },
  { name: "Norge", code: "NO", dial_code: "+47", phone_digits_count: "8~8" },
  { name: "عمان", code: "OM", dial_code: "+968", phone_digits_count: "8~8" },
  {
    name: "Pakistan",
    code: "PK",
    dial_code: "+92",
    phone_digits_count: "10~10",
  },
  { name: "Palau", code: "PW", dial_code: "+680", phone_digits_count: "7~7" },
  { name: "فلسطين", code: "PS", dial_code: "+970", phone_digits_count: "9~9" },
  { name: "Panamá", code: "PA", dial_code: "+507", phone_digits_count: "8~8" },
  {
    name: "Papua Niugini",
    code: "PG",
    dial_code: "+675",
    phone_digits_count: "11~11",
  },
  {
    name: "Paraguay",
    code: "PY",
    dial_code: "+595",
    phone_digits_count: "10~10",
  },
  { name: "Perú", code: "PE", dial_code: "+51", phone_digits_count: "11~11" },
  {
    name: "Pilipinas",
    code: "PH",
    dial_code: "+63",
    phone_digits_count: "10~10",
  },
  {
    name: "Pitcairn Islands",
    code: "PN",
    dial_code: "+64",
    phone_digits_count: "10~10",
  },
  { name: "Polska", code: "PL", dial_code: "+48", phone_digits_count: "9~9" },
  {
    name: "Portugal",
    code: "PT",
    dial_code: "+351",
    phone_digits_count: "9~9",
  },
  {
    name: "Puerto Rico",
    code: "PR",
    dial_code: "+1939",
    phone_digits_count: "15~15",
  },
  {
    name: "Puerto Rico",
    code: "PR",
    dial_code: "+1787",
    phone_digits_count: "15~15",
  },
  { name: "قطر", code: "QA", dial_code: "+974", phone_digits_count: "8~8" },
  { name: "România", code: "RO", dial_code: "+40", phone_digits_count: "9~9" },
  { name: "Россия", code: "RU", dial_code: "+7", phone_digits_count: "10~10" },
  { name: "Rwanda", code: "RW", dial_code: "+250", phone_digits_count: "9~9" },
  {
    name: "La Réunion",
    code: "RE",
    dial_code: "+262",
    phone_digits_count: "9~9",
  },
  {
    name: "Saint-Barthélemy",
    code: "BL",
    dial_code: "+590",
    phone_digits_count: "9~9",
  },
  {
    name: "Saint Helena",
    code: "SH",
    dial_code: "+290",
    phone_digits_count: "4~4",
  },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    dial_code: "+1869",
    phone_digits_count: "7~7",
  },
  {
    name: "Saint Lucia",
    code: "LC",
    dial_code: "+1758",
    phone_digits_count: "7~7",
  },
  {
    name: "Saint-Martin",
    code: "MF",
    dial_code: "+590",
    phone_digits_count: "9~9",
  },
  {
    name: "Saint-Pierre-et-Miquelon",
    code: "PM",
    dial_code: "+508",
    phone_digits_count: "6~6",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    dial_code: "+1784",
    phone_digits_count: "7~7",
  },
  { name: "Samoa", code: "WS", dial_code: "+685", phone_digits_count: "7~7" },
  {
    name: "San Marino",
    code: "SM",
    dial_code: "+378",
    phone_digits_count: "10~10",
  },
  {
    name: "São Tomé e Príncipe",
    code: "ST",
    dial_code: "+239",
    phone_digits_count: "7~7",
  },
  {
    name: "العربية السعودية",
    code: "SA",
    dial_code: "+966",
    phone_digits_count: "9~9",
  },
  { name: "Sénégal", code: "SN", dial_code: "+221", phone_digits_count: "9~9" },
  {
    name: "Србија",
    code: "RS",
    dial_code: "+381",
    phone_digits_count: "12~12",
  },
  {
    name: "Seychelles",
    code: "SC",
    dial_code: "+248",
    phone_digits_count: "6~6",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    dial_code: "+232",
    phone_digits_count: "8~8",
  },
  {
    name: "Singapore",
    code: "SG",
    dial_code: "+65",
    phone_digits_count: "12~12",
  },
  {
    name: "Slovensko",
    code: "SK",
    dial_code: "+421",
    phone_digits_count: "9~9",
  },
  {
    name: "Slovenija",
    code: "SI",
    dial_code: "+386",
    phone_digits_count: "8~8",
  },
  {
    name: "Solomon Islands",
    code: "SB",
    dial_code: "+677",
    phone_digits_count: "5~5",
  },
  {
    name: "Soomaaliya",
    code: "SO",
    dial_code: "+252",
    phone_digits_count: "8~8",
  },
  {
    name: "South Africa",
    code: "ZA",
    dial_code: "+27",
    phone_digits_count: "9~9",
  },
  {
    name: "South Sudan",
    code: "SS",
    dial_code: "+211",
    phone_digits_count: "9~9",
  },
  {
    name: "South Georgia",
    code: "GS",
    dial_code: "+500",
    phone_digits_count: "15~15",
  },
  { name: "España", code: "ES", dial_code: "+34", phone_digits_count: "9~9" },
  {
    name: "Sri Lanka",
    code: "LK",
    dial_code: "+94",
    phone_digits_count: "9~9",
  },
  { name: "السودان", code: "SD", dial_code: "+249", phone_digits_count: "9~9" },
  {
    name: "Suriname",
    code: "SR",
    dial_code: "+597",
    phone_digits_count: "7~7",
  },
  {
    name: "Svalbard og Jan Mayen",
    code: "SJ",
    dial_code: "+47",
    phone_digits_count: "8~8",
  },
  {
    name: "Swaziland",
    code: "SZ",
    dial_code: "+268",
    phone_digits_count: "8~8",
  },
  {
    name: "Sverige",
    code: "SE",
    dial_code: "+46",
    phone_digits_count: "13~13",
  },
  {
    name: "Schweiz",
    code: "CH",
    dial_code: "+41",
    phone_digits_count: "12~12",
  },
  { name: "سوريا", code: "SY", dial_code: "+963", phone_digits_count: "10~10" },
  { name: "臺灣", code: "TW", dial_code: "+886", phone_digits_count: "9~9" },
  {
    name: "Тоҷикистон",
    code: "TJ",
    dial_code: "+992",
    phone_digits_count: "9~9",
  },
  {
    name: "Tanzania",
    code: "TZ",
    dial_code: "+255",
    phone_digits_count: "9~9",
  },
  {
    name: "ประเทศไทย",
    code: "TH",
    dial_code: "+66",
    phone_digits_count: "9~9",
  },
  {
    name: "Timor-Leste",
    code: "TL",
    dial_code: "+670",
    phone_digits_count: "7~7",
  },
  { name: "Togo", code: "TG", dial_code: "+228", phone_digits_count: "8~8" },
  { name: "Tokelau", code: "TK", dial_code: "+690", phone_digits_count: "4~4" },
  { name: "Tonga", code: "TO", dial_code: "+676", phone_digits_count: "7~7" },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    dial_code: "+1868",
    phone_digits_count: "7~7",
  },
  { name: "تونس", code: "TN", dial_code: "+216", phone_digits_count: "8~8" },
  {
    name: "Türkiye",
    code: "TR",
    dial_code: "+90",
    phone_digits_count: "10~10",
  },
  {
    name: "Türkmenistan",
    code: "TM",
    dial_code: "+993",
    phone_digits_count: "8~8",
  },
  {
    name: "Turks and Caicos Islands",
    code: "TC",
    dial_code: "+1649",
    phone_digits_count: "7~7",
  },
  { name: "Tuvalu", code: "TV", dial_code: "+688", phone_digits_count: "6~6" },
  { name: "Uganda", code: "UG", dial_code: "+256", phone_digits_count: "9~9" },
  { name: "Україна", code: "UA", dial_code: "+380", phone_digits_count: "9~9" },
  {
    name: "دولة الإمارات العربية المتحدة",
    code: "AE",
    dial_code: "+971",
    phone_digits_count: "9~9",
  },
  {
    name: "United Kingdom",
    code: "GB",
    dial_code: "+44",
    phone_digits_count: "10~10",
  },
  {
    name: "United States",
    code: "US",
    dial_code: "+1",
    phone_digits_count: "10~10",
  },
  {
    name: "Uruguay",
    code: "UY",
    dial_code: "+598",
    phone_digits_count: "11~11",
  },
  {
    name: "O‘zbekiston",
    code: "UZ",
    dial_code: "+998",
    phone_digits_count: "9~9",
  },
  { name: "Vanuatu", code: "VU", dial_code: "+678", phone_digits_count: "7~7" },
  {
    name: "Venezuela",
    code: "VE",
    dial_code: "+58",
    phone_digits_count: "10~10",
  },
  {
    name: "Việt Nam",
    code: "VN",
    dial_code: "+84",
    phone_digits_count: "11~11",
  },
  {
    name: "British Virgin Islands",
    code: "VG",
    dial_code: "+1284",
    phone_digits_count: "7~7",
  },
  {
    name: "United States Virgin Islands",
    code: "VI",
    dial_code: "+1340",
    phone_digits_count: "7~7",
  },
  {
    name: "Wallis et Futuna",
    code: "WF",
    dial_code: "+681",
    phone_digits_count: "6~6",
  },
  { name: "اليَمَن", code: "YE", dial_code: "+967", phone_digits_count: "9~9" },
  { name: "Zambia", code: "ZM", dial_code: "+260", phone_digits_count: "9~9" },
  {
    name: "Zimbabwe",
    code: "ZW",
    dial_code: "+263",
    phone_digits_count: "9~9",
  },
];
